version: "3.3"
services:
    fetcher:
        image: localhost:5000/ulysseus/metadata-fetcher:latest
        restart: unless-stopped

        volumes:
            - metadata:/var/lib/metadata

    shibd:
        image: localhost:5000/ulysseus/shibd:3.1
        restart: unless-stopped

        depends_on:
            - fetcher

        secrets:
            - credential-resolver.crt
            - credential-resolver.key

        volumes:
            - metadata:/var/lib/metadata
            - ./shibd/etc/:/etc/shibboleth
            - shibd_runtime:/var/run/shibboleth

        environment:
            - URL_DIRECTORY_ON_WEB_SERVER=${URL_DIRECTORY_ON_WEB_SERVER}

    moodle:
        image: localhost:5000/ulysseus/moodle:3.10
        restart: unless-stopped

        depends_on:
            - shibd

        ports:
            - 4243:443

        secrets:
          - self-signed.crt
          - self-signed.key
          - moodle-db.pass

        volumes:
            - ./shibd/etc/:/etc/shibboleth
            - shibd_runtime:/var/run/shibboleth
            - ${MOODLE_DATA_DIR}:/var/www/moodledata
            - ${MOODLE_RUNTIME_DIR}:/var/www/html/${URL_DIRECTORY_ON_WEB_SERVER}
            - ./moodle/config.php:/var/www/html/${URL_DIRECTORY_ON_WEB_SERVER}/config.php

        environment:
            - URL_DIRECTORY_ON_WEB_SERVER=${URL_DIRECTORY_ON_WEB_SERVER}

secrets:
    self-signed.crt:
        file: ${HTTPS_SERVER_CERTIFICATE}
    self-signed.key:
        file: ${HTTPS_SERVER_PKEY}
    credential-resolver.crt:
        file: ${SHIBBOLETH_SP_CERTIFICATE}
    credential-resolver.key:
        file: ${SHIBBOLETH_SP_PKEY}
    moodle-db.pass:
        file: ${MYSQL_PASSWORD_FILE}

volumes:
    moodle_data:
    shibd_runtime:
    metadata:
